name: Build
on: push

jobs:
  run_pwsh:
    name: Run Powershell Script
    runs-on: windows-latest

    steps:
    - name: Setup Azure Infrastructure
      working-directory: AzureScripts
      shell: pwsh
      run: |
        .\BicepScriptDeployment.ps1
  
