name: Build
on: 
  push:
    paths-ignore: 
      - 'log.txt'

jobs:
  run_pwsh:
    name: Setup Azure Infrastructure
    runs-on: windows-latest

    steps:
    - name: Run Powershell Script $ Log
    #   working-directory: .\AzureScripts
      shell: pwsh
      run: |
        echo Running File...
        # .\BicepScriptDeployment.ps1
        status=$(BicepScriptDeployment.ps1 > log.txt 2>&1; echo $?)
        cat log.txt
        echo ::set-output name=status::$status

    # - name: Collect Logs
    #   id: log
    #   run: |
    #     status=$(BicepScriptDeployment.ps1 > log.txt 2>&1; echo $?)
    #     cat log.txt
    #     echo ::set-output name=status::$status
    - name: Commit Log
      run: |
          git config --global user.name 'himeenthusiast'
          git config --global user.email 'piantonibella@gmail.com'
          git add -A
          git checkout master
          git diff-index --quiet HEAD || git commit -am "deploy workflow logs"
          git push

      
  
#   error_log:
#       name: Log Workflow Errors
#       runs-on: windows-latest

#       steps:
#       -  name: 
