name: Build
on: 
  push:
    paths-ignore: 
      - 'log.txt'

jobs:
  run_pwsh:
    name: Setup Azure Infrastructure
    runs-on: windows-latest

    steps:
    - name: View Directory
      run: |
       echo Viewing Directory... 
       ls

    - name: Run Powershell Script
    #   working-directory: .\AzureScripts
      shell: pwsh
      run: |
        echo Running File...
        .\BicepScriptDeployment.ps1