name: Build
on: 
  push:
    paths-ignore: 
      - 'log.txt'

jobs:
  run_pwsh:
    name: Setup Azure Infrastructure
    runs-on: windows-latest

    steps:
    - name: Run Powershell Script
    #   working-directory: .\AzureScripts
      shell: pwsh
      run: |
        echo Running File...
        dir > log.txt
        echo $(./log.txt)
        .\BicepScriptDeployment.ps1