name: Build
on: 
  push:
    paths-ignore: 
      - 'log.txt'

jobs:
  run_pwsh:
    name: Setup Azure Infrastructure
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run Powershell Script
      shell: pwsh
      run: |
        echo Running File...
        .\BicepScriptDeployment.ps1